### ISSUE TITLE
OpenSSL has removed access to X509 struct members

### ISSUE THREAD

**Issue by mikeb01** [boothj5/libmesode#10]
This causes breakage when compiling against the latest OpenSSL.
```
src/tls_openssl.c: In function ‘_x509_to_tlscert’:
src/tls_openssl.c:180:2: error: ‘alg_nid’ undeclared (first use in this function)
  alg_nid = OBJ_obj2nid(cert->sig_alg->algorithm);
  ^~~~~~~
src/tls_openssl.c:180:2: note: each undeclared identifier is reported only once for each function it appears in
src/tls_openssl.c:180:28: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  alg_nid = OBJ_obj2nid(cert->sig_alg->algorithm);
```

**Comment by timhughes** [comment]
Workaround 
https://github.com/boothj5/profanity/issues/960

**Comment by Neo-Oli** [comment]
Is there also a workaround that works on debian/raspian?

**Comment by kokbira** [comment]
Me too:
```
src/tls_openssl.c:171:32: error: dereferencing pointer to incomplete type ‘X509’ {aka ‘struct x509_st’}
  int alg_nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                                ^~
```
When installing Profanity with helper script on Fedora29 (http://www.profanity.im/install.html#installscript)...

**Comment by jubalh** [comment]
@kokbira please don't use that helper script for now.
boothj5 created it some time ago and I don't thin kit's up to date.
It checks out libmesode 0.9.1 but you need 0.9.2 with which everything should work fine.

I don't have access to the webserver so I can't update the script there.

**Comment by jubalh** [comment]
@boothj5 maybe migrating profanity.im would be a good thing to do. Then we could just push to https://github.com/boothj5/www_profanity_im and profanity.im would be up to date. Since this is not done I'll have to ping you now again :-)

Can you please update profanity.im? I just pushed a fix to `install-all.sh` so it checks out libmesode 0.9.2

And https://github.com/boothj5/profanity/issues/1028 is also something that should be fixed regarding the website. Migrating to GH Pages could also make things easier here.

**Comment by jubalh** [comment]
@kokbira please tell me whether checking out libmesode 0.9.2 helps.

**Comment by jubalh** [comment]
Will close this due to inactivity. Feel free to reopen.
